### ISSUE TITLE
Wallpaper

### ISSUE THREAD

**Issue by TQMatvey** [alec-kr/i3wm-files#2]
Hey, this setup looks very great! Couldnt find the wallpaper in Configs, gonna search on google for now

**Comment by alec-kr** [comment]
The wallpaper can be found [here] (https://www.goodfon.com/wallpaper/synthpop-synth-retrowave-stas-fedorov-setka-muzyka-darkwave.html). I will add it in a PR soon.

**Comment by alec-kr** [comment]
Update: The wallpaper has been added to the main directory of the repo. This issue will now be closed.

Thank you for pointing out that the wallpaper was not in the repo 😄

**Comment by TQMatvey** [comment]
tysm
